### ISSUE TITLE
PM2启动报错

### ISSUE THREAD

**Issue by jguang** [ksc-fx/record#1]
Cluster mode下pm2启动出错,服务启动不了
```shell
2018-03-14 14:56:10: App name:nodebase id:2 online
path.js:1182
          cwd = process.cwd();
                        ^

Error: ENOENT: no such file or directory, uv_cwd
    at Object.resolve (path.js:1182:25)
    at Function.Module._resolveLookupPaths (module.js:416:17)
    at Function.Module._resolveFilename (module.js:530:20)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/data/deploy/node-v8.9.3-linux-x64/lib/node_modules/pm2/lib/ProcessContainer.js:13:15)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
2018-03-14 14:56:10: App name:nodebase id:2 disconnected
2018-03-14 14:56:10: App [nodebase] with id [2] and pid [24733], exited with code [1] via signal [SIGINT]

**Comment by jguang** [comment]
参考issues解决：
https://github.com/Unitech/pm2/issues/2057
